import type { Project, Activity, Profile } from '../types';

export const fallbackProjects: Project[] = [
  {
    id: '1',
    title: 'DocSignerHub',
    slug: 'docsignerhub',
    description: 'Digital signature SaaS platform with AI clause analysis, blockchain notarisation, visual workflow builder, and Stripe payment integration. 140+ REST API endpoints.',
    techStack: ['.NET 8', 'React', 'SQL Server', 'Azure', 'Stripe', 'OpenAI'],
    githubUrl: 'https://github.com/rajibmahata/DocumentSigningPlatform',
    liveUrl: 'https://docsignerhub.com',
    status: 'development',
    createdAt: new Date(Date.now() - 90 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    lastCommitAt: new Date(Date.now() - 3 * 3600000).toISOString(),
  },
  {
    id: '2',
    title: 'AI Avatar RAG Platform',
    slug: 'ai-avatar-rag',
    description: 'Enterprise AI knowledge retrieval platform with avatar-based interaction, semantic search, and RAG pipelines.',
    techStack: ['Python', 'FastAPI', 'OpenAI', 'RAG', 'Vector DB', 'React'],
    githubUrl: 'https://github.com/rajibmahata/AI-Avatar-RAG-Platform',
    liveUrl: null,
    status: 'development',
    createdAt: new Date(Date.now() - 120 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    lastCommitAt: new Date(Date.now() - 2 * 86400000).toISOString(),
  },
  {
    id: '3',
    title: 'Solicitor Case Management',
    slug: 'solicitor-cms',
    description: 'Legal enterprise workflow platform for case tracking, document management, and client communication.',
    techStack: ['.NET 8', 'Blazor', 'SQL Server', 'Azure', 'Cosmos DB'],
    githubUrl: 'https://github.com/rajibmahata/SolicitorCaseManagementSystem',
    liveUrl: null,
    status: 'planning',
    createdAt: new Date(Date.now() - 180 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    lastCommitAt: new Date(Date.now() - 7 * 86400000).toISOString(),
  },
  {
    id: '4',
    title: 'Rajib Labs Platform',
    slug: 'rajiblabs',
    description: 'AI-powered portfolio and software lab. Auto-populated from GitHub, managed by OpenClaw agents. This very platform.',
    techStack: ['.NET 8', 'React', 'TypeScript', 'Tailwind CSS', 'SQLite', 'OpenClaw'],
    githubUrl: 'https://github.com/rajibmahata/rajiblabs-platform',
    liveUrl: 'http://rajibmahata143-001-site1.mtempurl.com',
    status: 'development',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    lastCommitAt: new Date().toISOString(),
  },
];

export const fallbackActivities: Activity[] = [
  {
    id: 'a1',
    projectId: '4',
    type: 'milestone',
    title: 'Rajib Labs Platform — Deployed',
    description: 'React frontend live on SmarterASP.NET hosting, 7-agent AI workforce operational',
    timestamp: new Date().toISOString(),
  },
  {
    id: 'a2',
    projectId: '1',
    type: 'commit',
    title: 'DocSignerHub — Auth middleware refactored',
    description: 'Rate limiting, API hardening, session management improvements',
    timestamp: new Date(Date.now() - 3 * 3600000).toISOString(),
  },
  {
    id: 'a3',
    projectId: '2',
    type: 'milestone',
    title: 'RAG Platform — Embedding pipeline live',
    description: 'Hybrid vector search with semantic ranking operational',
    timestamp: new Date(Date.now() - 24 * 3600000).toISOString(),
  },
  {
    id: 'a4',
    projectId: '1',
    type: 'deploy',
    title: 'DocSignerHub — Blog system shipped',
    description: 'AI-generated tutorial blogs live on docsignerhub.com/blog',
    timestamp: new Date(Date.now() - 2 * 86400000).toISOString(),
  },
  {
    id: 'a5',
    projectId: '3',
    type: 'commit',
    title: 'Solicitor CMS — Workflow module started',
    description: 'Visual case flow builder prototype in progress',
    timestamp: new Date(Date.now() - 5 * 86400000).toISOString(),
  },
  {
    id: 'a6',
    projectId: '4',
    type: 'commit',
    title: 'Rajib Labs — 7 AI agents live',
    description: 'UX + Architect + Dev + QA + DevOps + Monitor + Portfolio agents operational',
    timestamp: new Date(Date.now() - 3600000).toISOString(),
  },
];

export const fallbackProfile: Profile = {
  id: 'p1',
  fullName: 'Rajib Mahata',
  title: 'Senior Software Architect | AI & SaaS Platform Builder',
  bio: 'Independent software architect with 10+ years building production SaaS platforms, AI systems, and cloud-native applications. Specialising in .NET, Azure, and AI/LLM integrations.',
  skills: ['.NET 8/10', 'C#', 'ASP.NET Core', 'Blazor', 'React', 'Python FastAPI', 'Azure Cloud', 'Microservices', 'SQL Server', 'Cosmos DB', 'OpenAI/Gemini APIs', 'RAG Systems', 'Docker', 'GitHub Copilot'],
  socialLinks: {
    github: 'https://github.com/rajibmahata',
    linkedin: 'https://linkedin.com/in/rajib-mahata',
  },
};
