import type { Project, Activity, Profile, GitHubSummary, WipData } from '../types';

export const fallbackProjects: Project[] = [
  {
    id: '1',
    title: 'DocSignerHub',
    slug: 'docsignerhub',
    description: 'Digital signature SaaS platform with AI clause analysis, blockchain notarisation, visual workflow builder, and Stripe payment integration. 140+ REST API endpoints.',
    techStack: ['.NET 8', 'React', 'SQL Server', 'Azure', 'Stripe', 'OpenAI'],
    githubUrl: 'https://github.com/rajibmahata/DocumentSigningPlatform',
    liveUrl: 'https://docsignerhub.com',
    status: 'development',
    createdAt: new Date(Date.now() - 90 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    lastCommitAt: new Date(Date.now() - 3 * 3600000).toISOString(),
  },
  {
    id: '2',
    title: 'AI Avatar RAG Platform',
    slug: 'ai-avatar-rag',
    description: 'Enterprise AI knowledge retrieval platform with avatar-based interaction, semantic search, and RAG pipelines.',
    techStack: ['Python', 'FastAPI', 'OpenAI', 'RAG', 'Vector DB', 'React'],
    githubUrl: 'https://github.com/rajibmahata/AI-Avatar-RAG-Platform',
    liveUrl: null,
    status: 'development',
    createdAt: new Date(Date.now() - 120 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    lastCommitAt: new Date(Date.now() - 2 * 86400000).toISOString(),
  },
  {
    id: '3',
    title: 'Solicitor Case Management',
    slug: 'solicitor-cms',
    description: 'Legal enterprise workflow platform for case tracking, document management, and client communication.',
    techStack: ['.NET 8', 'Blazor', 'SQL Server', 'Azure', 'Cosmos DB'],
    githubUrl: 'https://github.com/rajibmahata/SolicitorCaseManagementSystem',
    liveUrl: null,
    status: 'planning',
    createdAt: new Date(Date.now() - 180 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    lastCommitAt: new Date(Date.now() - 7 * 86400000).toISOString(),
  },
  {
    id: '4',
    title: 'Rajib Labs Platform',
    slug: 'rajiblabs',
    description: 'AI-powered portfolio and software lab. Auto-populated from GitHub, managed by OpenClaw agents. This very platform.',
    techStack: ['.NET 8', 'React', 'TypeScript', 'Tailwind CSS', 'SQLite', 'OpenClaw'],
    githubUrl: 'https://github.com/rajibmahata/rajiblabs-platform',
    liveUrl: 'http://rajibmahata143-001-site1.mtempurl.com',
    status: 'development',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    lastCommitAt: new Date().toISOString(),
  },
];

export const fallbackActivities: Activity[] = [
  {
    id: 'a1',
    projectId: '4',
    type: 'milestone',
    title: 'Rajib Labs Platform — Deployed',
    description: 'React frontend live on SmarterASP.NET hosting, 7-agent AI workforce operational',
    timestamp: new Date().toISOString(),
  },
  {
    id: 'a2',
    projectId: '1',
    type: 'commit',
    title: 'DocSignerHub — Auth middleware refactored',
    description: 'Rate limiting, API hardening, session management improvements',
    timestamp: new Date(Date.now() - 3 * 3600000).toISOString(),
  },
  {
    id: 'a3',
    projectId: '2',
    type: 'milestone',
    title: 'RAG Platform — Embedding pipeline live',
    description: 'Hybrid vector search with semantic ranking operational',
    timestamp: new Date(Date.now() - 24 * 3600000).toISOString(),
  },
  {
    id: 'a4',
    projectId: '1',
    type: 'deploy',
    title: 'DocSignerHub — Blog system shipped',
    description: 'AI-generated tutorial blogs live on docsignerhub.com/blog',
    timestamp: new Date(Date.now() - 2 * 86400000).toISOString(),
  },
  {
    id: 'a5',
    projectId: '3',
    type: 'commit',
    title: 'Solicitor CMS — Workflow module started',
    description: 'Visual case flow builder prototype in progress',
    timestamp: new Date(Date.now() - 5 * 86400000).toISOString(),
  },
  {
    id: 'a6',
    projectId: '4',
    type: 'commit',
    title: 'Rajib Labs — 7 AI agents live',
    description: 'UX + Architect + Dev + QA + DevOps + Monitor + Portfolio agents operational',
    timestamp: new Date(Date.now() - 3600000).toISOString(),
  },
];

export const fallbackProfile: Profile = {
  id: 'p1',
  fullName: 'Rajib Mahata',
  title: 'Senior Software Architect | AI & SaaS Platform Builder',
  bio: 'Independent software architect with 10+ years building production SaaS platforms, AI systems, and cloud-native applications. Specialising in .NET, Azure, and AI/LLM integrations.',
  skills: ['.NET 8/10', 'C#', 'ASP.NET Core', 'Blazor', 'React', 'Python FastAPI', 'Azure Cloud', 'Azure DevOps', 'Microservices', 'CQRS & Design Patterns', 'SQL Server', 'Cosmos DB', 'OpenAI/Gemini APIs', 'RAG Systems', 'Docker', 'GitHub Copilot'],
  socialLinks: {
    github: 'https://github.com/rajibmahata',
    linkedin: 'https://linkedin.com/in/rajib-mahata',
  },
  career: [
    {
      company: 'Fortune 500 Healthcare',
      role: 'Solutions Architect',
      period: 'Aug 2019 – Present',
      client: 'Healthcare & Pharmacy (USA)',
      achievements: [
        'Led development of open APIs, reducing pharmacy vendor dependency by 100%',
        'Architected data lake on Azure for raw prescription/patient data ingestion and processing',
        'Automated Prescription Refill System — 30% faster processing, 40% fewer medication errors',
        'Vaccine Appointment System — streamlined COVID-19 immunization scheduling nationally',
        'Built Rule Engine (CQRS) on Azure PaaS processing 500K+ daily prescription events',
        'Deployed PWAs on Azure Cloud for secure, scalable pharmacy interfaces',
        'Integrated secure payment (MParks), barcode scanning, voice/SMS notifications',
      ],
      techStack: ['.NET 8', 'Blazor', 'Azure Functions', 'Logic Apps', 'Service Bus', 'Event Grid', 'Cosmos DB', 'Azure Data Factory', 'AngularJS', 'Open API'],
      color: 'var(--c-accent-blue)',
    },
    {
      company: 'Telecom Enterprise',
      role: 'Platform Engineer',
      period: 'Jul 2016 – Feb 2019',
      client: 'Telecommunications (USA)',
      achievements: [
        'Designed and built CMT application automating network equipment provisioning',
        'Reduced manual intervention by 30%, processing time by 40%',
        'Achieved 95% issue resolution within 24 hours via automated ticket system',
        'Built intuitive UI improving user satisfaction scores by 25%',
      ],
      techStack: ['ASP.NET MVC', 'WCF', 'Entity Framework', 'SQL Server', 'JavaScript'],
      color: 'var(--c-accent-teal)',
    },
    {
      company: 'Product Studio',
      role: 'Full-Stack Developer',
      period: 'Mar 2013 – Apr 2016',
      achievements: [
        'Built Corporate Hour — B2B media advertisement & trade platform',
        'Developed Cinematic Lens — product visual storytelling platform',
        'Created TRANSZOOM — car rental & TruckIt365 freight matching solution',
        'Full-stack ownership: database design to frontend deployment',
      ],
      techStack: ['ASP.NET MVC', 'SQL Server', 'JavaScript', 'HTML/CSS', 'AJAX'],
      color: 'var(--c-accent-gold)',
    },
  ],
};

export const fallbackGitHubSummary: GitHubSummary = {
  stats: [
    { value: '247', label: 'contributions', icon: '📊' },
    { value: '12', label: 'repos', icon: '📦' },
    { value: '3', label: 'languages', icon: '🔤' },
    { value: 'Kolkata', label: 'location', icon: '📍' },
  ],
  topRepos: [
    { name: 'DocSignerHub', language: 'C#', stars: 12, forks: 3, updated: '2 days ago', langColor: '#178600' },
    { name: 'AI-Avatar-RAG-Platform', language: 'Python', stars: 8, forks: 2, updated: '5 hours ago', langColor: '#3572A5' },
    { name: 'FoodFleet', language: 'TypeScript', stars: 6, forks: 1, updated: '3 weeks ago', langColor: '#3178C6' },
    { name: 'SolicitorCaseManagementSystem', language: 'C#', stars: 5, forks: 1, updated: '1 month ago', langColor: '#178600' },
    { name: 'rajiblabs-platform', language: 'TypeScript', stars: 4, forks: 0, updated: 'just now', langColor: '#3178C6' },
    { name: 'BudgetEase', language: 'C#', stars: 3, forks: 0, updated: '2 months ago', langColor: '#178600' },
  ],
};

export const fallbackWipData: WipData = {
  projects: [
    {
      name: 'DocSignerHub v2',
      stack: '.NET 8 · Blazor · Azure · SQL · HMAC-SHA256',
      progress: 72,
      lastActivity: '1 week ago',
      status: 'live' as const,
    },
    {
      name: 'ARIA Phase 2',
      stack: 'FastAPI · GPT-4o · ChromaDB · React · LangChain',
      progress: 48,
      lastActivity: '2 weeks ago',
      status: 'wip' as const,
    },
    {
      name: 'AgentTube (SahajSeva)',
      stack: 'React PWA · GPT-4o · DeepSeek V3 · .NET 8',
      progress: 30,
      lastActivity: '3 weeks ago',
      status: 'wip' as const,
    },
  ],
  commits: [
    { hash: '2928dcc', message: 'docs: add ftp deploy instructions', repoName: 'rajiblabs-platform', timestamp: '4 days ago' },
    { hash: '2623107', message: 'feat: modernize RajibLabs homepage redesign', repoName: 'rajiblabs-platform', timestamp: '6 days ago' },
    { hash: 'f786b34', message: 'devops: restore CI/CD pipelines + security headers', repoName: 'rajiblabs-platform', timestamp: '7 days ago' },
    { hash: '3198890', message: 'feat: batch gap analysis — 4 new projects + services', repoName: 'rajiblabs-platform', timestamp: '7 days ago' },
    { hash: '6363039', message: 'feat: added 8 enterprise projects from resume', repoName: 'rajiblabs-platform', timestamp: '8 days ago' },
    { hash: '3bcef5b', message: 'feat: unified Button, project detail modals', repoName: 'rajiblabs-platform', timestamp: '9 days ago' },
  ],
};
